namespace AdvancedBot.Core.Entities.Enums
{
    public enum LogAction
    {
        Ban = 0,
        Unban = 1,
        AddBeta = 2,
        RemoveBeta = 3,
        UpdateEmail = 4,
        UpdateName = 5,
        GetFull = 6,
        GetChipsBought = 7,
        AddChips = 8,
        AddItem = 9,
        KickOffline = 10,
        Reset = 11,
        GiveRole = 12,
        RenameAlliance = 13,
        RemoveUserFromAlliance = 14,
        MakeUserAllianceOwner = 15,
        GetWarlogs = 16,
        EnableMaintenance = 17,
        ReloadRules = 18,
        AddXp = 19,
        GetTelemetry = 20,
        RunKicker = 21,
        ResetHelps = 22,
        ForceWar = 23,
        ForceStopWar = 24,
        AddEmulate = 25,
        RemoveEmulate = 26,
        GetAccounts = 27,
        GetChipsSpent = 28,
        Compensate = 29,
    }
}
