name: Feature
description: An enhancement or feature
title: "feature: "
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A step-by-step description of the suggested feature/enhancement.
      placeholder: When comparing two players, it would be nice to see...
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Please include any screenshots which would help demonstrate the steps
        and point out which parts the feature is related to
