name: Console CICD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x
    - name: Install dependencies
      run: dotnet restore src/AdvancedBot.Console/AdvancedBot.Console.csproj
    - name: Build
      run: dotnet build src/AdvancedBot.Console/AdvancedBot.Console.csproj --configuration Release
